# Generated by Django 4.1.7 on 2023-03-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_database_timeslot_alter_location_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='station_name',
        ),
    ]
