# Generated by Django 4.1.7 on 2023-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_database_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('time_slot', models.CharField(max_length=50)),
                ('shipments', models.CharField(max_length=50)),
                ('max_capacity', models.IntegerField()),
                ('min_radius', models.CharField(max_length=50)),
            ],
        ),
    ]
