# Generated by Django 4.1.7 on 2023-03-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_trips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='shipments',
            new_name='shipment',
        ),
    ]
