# Generated by Django 4.1.7 on 2023-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10)),
                ('time_slot', models.CharField(max_length=20)),
                ('radius', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('num_trips', models.IntegerField()),
            ],
        ),
    ]
