# Generated by Django 4.1.7 on 2023-03-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_create_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=100)),
                ('timeslot', models.CharField(max_length=100)),
                ('tripcapacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pincode', models.CharField(max_length=10)),
                ('timeslot', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='create_trips',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
