# Generated by Django 4.1.7 on 2023-03-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_create_trip_shipment_delete_create_trips_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_trip',
            new_name='Neworder_database',
        ),
    ]
