# Generated by Django 4.1.7 on 2023-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_create_trip_neworder_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder_database',
            name='radius',
            field=models.DecimalField(decimal_places=6, default=123, max_digits=9),
            preserve_default=False,
        ),
    ]
