# Generated by Django 4.1.7 on 2023-03-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_neworder_database_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder_database',
            name='radius',
        ),
    ]
