# Generated by Django 4.1.7 on 2023-03-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_neworder_database_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder_database',
            name='radius',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
