# Generated by Django 4.1.7 on 2023-03-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_neworder_database_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder_database',
            name='trip_score',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
