# Generated by Django 4.1.7 on 2023-04-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_trip_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
