# Generated by Django 4.1.7 on 2023-04-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_trip_latitude_alter_trip_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder_database',
            name='count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='neworder_database',
            name='locations',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='neworder_database',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
