# Generated by Django 4.1.7 on 2023-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_tripcapacity_neworder_database_trip_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random',
            name='latitude',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='random',
            name='longitude',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
    ]
